# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#persistentvolumeclaim-v1-core

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-persistent-volume-claim
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${DEMO_PREFIX}-azurefile
