apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-persistent-volume-claim
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${DEMO_PREFIX}-azurefile
