apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2-persistent-volume
  labels:
    assign-to: database
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/vda1/db2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
