# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#persistentvolume-v1-core

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-persistent-volume
  labels:
    type: local
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/vda1/postgresql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
