# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#storageclass-v1-storage-k8s-io

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ${DEMO_PREFIX}-azurefile
  namespace: ${DEMO_NAMESPACE}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
provisioner: kubernetes.io/azure-file
