image:
  registry: ${DOCKER_REGISTRY_URL}
  tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

imagePullSecrets:
  - name: ${DOCKER_REGISTRY_SECRET}

senzing:
  databaseUrl: "postgresql://postgres:postgres@${DEMO_PREFIX}-postgresql:5432/G2"
  persistentVolumeClaim: senzing-persistent-volume-claim
  subcommand: service
