image:
  registry: ${DOCKER_REGISTRY_URL}
  tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

imagePullSecrets:
  - name: ${DOCKER_REGISTRY_SECRET}

senzing:
  databaseUrl: "mysql://g2:g2@${DEMO_PREFIX}-mysql:3306/G2"
  persistentVolumeClaim: senzing-persistent-volume-claim
  subcommand: service
