# See https://github.com/Senzing/charts/tree/master/charts/senzing-configurator#parameters

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

  senzing:
    databaseUrl: "mysql://g2:g2@${DEMO_PREFIX}-bitnami-mysql:3306/G2"
    persistentVolumeClaim: senzing-persistent-volume-claim
    subcommand: service
