# See https://github.com/Senzing/charts/tree/main/charts/senzing-configurator#parameters

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    repository: senzing/configurator-mysql
    tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

  senzing:
    engineConfigurationJson: >-
      {
        "PIPELINE": {
          "CONFIGPATH": "/etc/opt/senzing",
          "LICENSESTRINGBASE64": "${SENZING_LICENSE_BASE64_ENCODED}",
          "RESOURCEPATH": "/opt/senzing/g2/resources",
          "SUPPORTPATH": "/opt/senzing/data"
        },
        "SQL": {
          "BACKEND": "SQL",
          "CONNECTION": "mysql://g2:g2@${DEMO_PREFIX}-bitnami-mysql:3306/?schema=G2"
        }
      }
    subcommand: service
