# See https://github.com/Senzing/charts/tree/main/charts/senzing-configurator#parameters

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

  senzing:
    engineConfigurationJson: >-
      {
        "PIPELINE": {
          "CONFIGPATH": "/etc/opt/senzing",
          "LICENSESTRINGBASE64": "${SENZING_LICENSE_BASE64_ENCODED}",
          "RESOURCEPATH": "/opt/senzing/g2/resources",
          "SUPPORTPATH": "/opt/senzing/data"
        },
        "SQL": {
          "BACKEND": "SQL",
          "CONNECTION": "mssql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:1433/${DATABASE_DATABASE}"
        }
      }
    subcommand: service
