# See https://github.com/Senzing/charts/tree/main/charts/senzing-configurator#parameters

ingress:
  enabled: true

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

  podSecurityContext:
    enabled: true

  senzing:
    databaseUrl: "postgresql://${SENZING_TENANT}:${DATABASE_PASSWORD}@${DEMO_PREFIX}-bitnami-postgresql.${DEMO_NAMESPACE_ADMIN}.svc.cluster.local:5432/g2_${SENZING_TENANT}"
    persistentVolumeClaim: senzing-persistent-volume-claim
    subcommand: service

rbac:
  enabled: true

service:
  enabled: true

serviceAccount:
  enabled: true
