# See https://github.com/Senzing/charts/tree/main/charts/senzing-configurator#parameters

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

  senzing:
    databaseUrl: "postgresql://postgres:postgres@${DEMO_PREFIX}-bitnami-postgresql:5432/G2"
    persistentVolumeClaim: senzing-persistent-volume-claim
    subcommand: service
