# See https://github.com/Senzing/charts/tree/main/charts/senzing-configurator#parameters

ingress:
  enabled: false

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

  podSecurityContext:
    enabled: true

  senzing:
    engineConfigurationJson: >-
      {
        "PIPELINE": {
          "CONFIGPATH": "/etc/opt/senzing",
          "RESOURCEPATH": "/opt/senzing/g2/resources",
          "SUPPORTPATH": "/opt/senzing/data"
        },
        "SQL": {
          "BACKEND": "SQL",
          "CONNECTION": "postgresql://${SENZING_TENANT}:${DATABASE_PASSWORD}@$bitnami-postgresql.${DEMO_NAMESPACE_ADMIN}.svc.cluster.local:5432:g2_${SENZING_TENANT}"
        }
      }
    subcommand: service

rbac:
  enabled: true

service:
  enabled: true

serviceAccount:
  enabled: true
