# See https://github.com/Senzing/charts/tree/main/charts/senzing-configurator#parameters

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    tag: ${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR}

  senzing:
    engineConfigurationJson: >-
      {
        "PIPELINE": {
          "CONFIGPATH": "/etc/opt/senzing",
          "RESOURCEPATH": "/opt/senzing/g2/resources",
          "SUPPORTPATH": "/opt/senzing/data"
        },
        "SQL": {
          "BACKEND": "SQL",
          "CONNECTION": "postgresql://postgres:postgres@${DEMO_PREFIX}-bitnami-postgresql:5432:G2"
        }
      }
    subcommand: service
