# See https://github.com/Senzing/charts/tree/main/charts/swaggerapi-swagger-ui#parameters

main:

  image:
    registry: ${DOCKER_REGISTRY_URL}
    tag: ${SENZING_DOCKER_IMAGE_VERSION_SWAGGERAPI_SWAGGER_UI}

  swaggerui:
    openApiSpecUrl: https://raw.githubusercontent.com/Senzing/senzing-rest-api-specification/main/senzing-rest-api.yaml
